name: Build using AMD drivers

on:
  push:
    branches: [ master, dev*, ow*, test* ]
  pull_request:
    branches: [ master, dev*, ow*, test* ]

jobs:

  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ ubuntu-24.04 ]

    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        
    - uses: actions/checkout@v6

    - name: Install AMD OpenCL libraries needed for Sibernetic
      run: |

        lscpu

        echo "Installing OpenCL Drivers and Java (for jNeuroML)"
        
        sudo apt-get update --fix-missing
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
          build-essential \
          git \
          python3-dev \
          default-jre-headless \
          libopengl0 \
          freeglut3-dev \
          libglu1-mesa-dev \
          clinfo \
          ocl-icd-libopencl1 \
          ocl-icd-opencl-dev \
          opencl-clhpp-headers \
          pocl-opencl-icd \
          mesa-opencl-icd

        echo "OpenCL Driver Installation Complete"

        echo "CLINFO:"
        clinfo

    - name: Build Sibernetic
      run: |

        python -V
        ls -alt /usr/bin/python*
        ls -alt
        make clean
        make

    - name: Print Sibernetic help
      run: |
        ./Release/Sibernetic -h

    - name: Run quick Sibernetic test
      run: |
        ldd ./Release/Sibernetic

        ./Release/Sibernetic -no_g timelimit=0.001

    - name: Run tests
      run: |
        pip install -r requirements.txt
      
        pip install OSBModelValidation # For the OMV tests
        pip list
        which nrniv
        export NEURON_HOME=/home/runner/.local

        ./test.sh -all

        omv find 
        omv all -V 

    - name: Generated file info
      run: |
        
        ls -alth simulations/*
        more simulations/test_*/report.json


    - name: Final version info
      run: |
        
        python -V
        omv list -V 
        pip list
